### ISSUE TITLE
Follow automatic-pancake

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/lightbright#7]

**Comment by lance** [comment]
Can you be more specific about what items from automatic-pancake are missing? I've added an issue for a [CONTRIBUTING.md](https://github.com/bucharest-gold/lightbright/issues/8). What else?

**Comment by helio-frota** [comment]
lightbright has coverage badge.

> Badges [ It would be good to keep uniformity between projects. [Amount and types] ]

https://github.com/bucharest-gold/automatic-pancake/issues/5#issuecomment-245017883

So since we are using istanbul , the coverage badge is basically required [ right? ]

Also, lightbright is using custom test approach so in this case tap-spec not required.

Then the missing part is README.

**Comment by helio-frota** [comment]
lightbright missing only vulnerability and npm badges on readme, I'm going to add and close.
